version: 2
# refs: https://zenn.dev/yuki0920/articles/9af3a7581193bf
#       https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]