name: "Run Lint, Tests, and Build"

on:
  push:
    branches:
      - develop
    paths:
      - "src/**"
      - "!src/**/stories/**"
      - "!src/**/assets/**"
      - "!src/**/constants/**"
  pull_request:
    branches:
      - develop
    paths:
      - "src/**"
      - "!src/**/stories/**"
      - "!src/**/assets/**"
      - "!src/**/constants/**"

permissions:
  pull-requests: write
  contents: read

env:
  WORKING_DIR: '.'
  CACHE_NAME: node_modules_cache

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: " Use Node.js 20.10.0"
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: npm

      - name: cache-node-modules
        uses: actions/cache@v4
        id: node_modules_cache_id
        with:
          path: ${{ env.WORKING_DIR }}/node_modules
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ hashFiles('${{ env.WORKING_DIR }}/package-lock.json') }}

      - name: npm-install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm i

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: " Use Node.js 20.10.0"
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: npm

      - name: restore-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.WORKING_DIR }}/node_modules
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ hashFiles('${{ env.WORKING_DIR }}/package-lock.json') }}

      - name: es-lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: " Use Node.js 20.10.0"
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: npm

      - name: restore-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.WORKING_DIR }}/node_modules
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ hashFiles('${{ env.WORKING_DIR }}/package-lock.json') }}

      - name: vitest-coverage
        run: npm run vitest:coverage

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.2.0
        with:
          json-summary-path: "./coverage/vitest/coverage-summary.json"
          json-final-path: "./coverage/vitest/coverage-final.json"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: " Use Node.js 20.10.0"
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: npm

      - name: restore-node_modules-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.WORKING_DIR }}/node_modules
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ hashFiles('${{ env.WORKING_DIR }}/package-lock.json') }}

      - name: build
        run: npm run build
